### ISSUE TITLE
Error: iptables.twopi: syntax error in line 294 near ':'

### ISSUE THREAD

**Issue by nrth3rnlb** [jekor/gressgraph#3] opened 2016-01-29 10:16 UTC
```
$ sudo iptables -L -vx | ./gressgraph > iptables.twopi
$ twopi -Tsvg iptables.twopi > iptables.svg
Error: iptables.twopi: syntax error in line 294 near ':'
```

Line 293 - 295

```
edge [color="#3288BD" fontcolor="#3288BD"  arrowhead=normal]
"any_anywhere" -> "any" [label=" Protocol "spt:bootps":bootpc"]
"any" -> "any" -> "any_anywhere"
```

**Comment by jekor** [comment] 2016-01-30 07:10
Thanks for the report. Looks like the parser wasn't prepared for a protocol name with a colon in it. Until I fix it you can work around it by using the `-n` (numeric) option, like `iptables -L -nvx`.

**Comment by jekor** [comment] 2016-02-03 08:12
Correction, I see that this is caused by a spt extra option and am working on a fix now.

**Comment by jekor** [comment] 2016-02-03 10:05
Fixed by https://github.com/jekor/gressgraph/commit/6bf0ea5983dfa00ba93904772a27039f73bc00e6

**Closed as completed by jekor** 2016-02-03 10:05 UTC

**Comment by nrth3rnlb** [comment] 2016-02-04 07:45
works, great. Thank you.

**Comment by mitchellkrogza** [comment] 2017-04-16 11:31
On Ubuntu 16.04.2 I get

```
~# iptables -L -vx | gressgraph > iptables.twopi
~# twopi -Tsvg iptables.twopi > iptables.svg
Error: iptables.twopi: syntax error in line 132 near ':'
```
